---
# todo: change to deployment
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nifi-ca
  namespace: nifi
  labels:
    app: nifi-ca
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: nifi-ca
  template:
    metadata:
      namespace: nifi
      labels:
        app: nifi-ca
    spec:
      containers:
        - name: nifi-ca
          image: image-registry.openshift-image-registry.svc:5000/nifi/nifi-ocp
          ports:
            - containerPort: 8443
              name: ca-client-port
          command:
            - bash
            - -c
            - |
              ../nifi-toolkit-current/bin/tls-toolkit.sh server -c nifi-ca-cs -t password
