
#!/bin/sh -e

# Run the tls-toolkit in client mode to generate the truststore and keystore
/opt/nifi/nifi-toolkit-current/bin/tls-toolkit.sh client -c "${CA_SERVER_HOSTNAME}" -t "${CA_SERVER_TOKEN}" --dn "CN=$(hostname -f), OU=NIFI"

# Use jq to extract the passwords form the config.json generated by the tls-toolkit
export KEYSTORE_PASSWORD=`jq -r '.keyStorePassword' ./config.json`
export KEY_PASSWORD=`jq -r '.keyPassword' ./config.json`
export KEYSTORE_PATH='./conf/keystore.jks'
export TRUSTSTORE_PASSWORD=`jq -r '.trustStorePassword' ./config.json`
export TRUSTSTORE_PATH='./conf/truststore.jks'

mv ./keystore.jks conf/
mv ./truststore.jks conf/